# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Home
email: petr.v.2019@mail.ru
description: Мой блог
baseurl: /simple
twitter_username:  
github_username: PetrVav 
# Build settings
markdown: kramdown
kramdown:
exclude:
- Gemfile
- Gemfile.lock

# Third-party services
# just leave someone empty to disable it
# google_analytics: 
disqus_shortname:

# used this for post_excerpt at index_page
excerpt_separator: <!--description-->
